name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:

  # ─────────────────────────────────────────
  # JOB 1 — Build and Push Images to ECR
  # ─────────────────────────────────────────
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push Auth Service
        run: |
          docker build -t auth-service ./backend/microservices/auth-service
          docker tag auth-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      - name: Build and Push User Service
        run: |
          docker build -t user-service ./backend/microservices/user-service
          docker tag user-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:latest

      - name: Build and Push Product Service
        run: |
          docker build -t product-service ./backend/microservices/product-service
          docker tag product-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/product-service:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/product-service:latest


  # ─────────────────────────────────────────
  # JOB 2 — Deploy to EKS
  # ─────────────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect kubectl to EKS cluster
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Create namespace
        run: |
          kubectl create namespace mern-microservices --dry-run=client -o yaml | kubectl apply -f -

      - name: Create ECR image pull secret
        run: |
          kubectl create secret docker-registry ecr-secret \
            --docker-server=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) \
            --namespace=mern-microservices \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply mongo secret
        run: |
          kubectl delete secret mongo-secret -n mern-microservices --ignore-not-found=true
          kubectl apply -f k8s-deployments/mongo-secret.yaml -n mern-microservices

      - name: Deploy all services
        run: |
          kubectl apply -f k8s-deployments/auth-service/deployment.yaml -n mern-microservices
          kubectl apply -f k8s-deployments/auth-service/service.yaml -n mern-microservices
          kubectl apply -f k8s-deployments/user-service/deployment.yaml -n mern-microservices
          kubectl apply -f k8s-deployments/user-service/service.yaml -n mern-microservices
          kubectl apply -f k8s-deployments/product-service/deployment.yaml -n mern-microservices
          kubectl apply -f k8s-deployments/product-service/service.yaml -n mern-microservices

      - name: Apply ingress
        run: |
          kubectl apply -f k8s-deployments/ingress.yaml -n mern-microservices

      - name: Wait for pods to start
        run: sleep 40

      - name: Check status
        run: |
          echo "=== Pods ==="
          kubectl get pods -n mern-microservices

          echo "=== Services ==="
          kubectl get svc -n mern-microservices

          echo "=== Auth logs ==="
          kubectl logs -n mern-microservices -l app=auth-service --tail=30

          echo "=== User logs ==="
          kubectl logs -n mern-microservices -l app=user-service --tail=30

          echo "=== Product logs ==="
          kubectl logs -n mern-microservices -l app=product-service --tail=30

          echo "=== Ingress URL ==="
          kubectl get ingress -n mern-microservices

          echo "=== Load Balancer Controller pods ==="
          kubectl get pods -n kube-system | grep aws-load-balancer

          echo "=== Ingress status ==="
          kubectl get ingress -n mern-microservices

          echo "=== Ingress details ==="
          kubectl describe ingress mern-ingress -n mern-microservices

