name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # ================= AUTH SERVICE =================
      - name: Build Auth Service Image
        run: |
          docker build -t auth-service ./backend/microservices/auth-service
          docker tag auth-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      - name: Push Auth Service Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      # ================= USER SERVICE =================
      - name: Build User Service Image
        run: |
          docker build -t user-service ./backend/microservices/user-service
          docker tag user-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:latest

      - name: Push User Service Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:latest

      # ================= PRODUCT SERVICE =================
      - name: Build Product Service Image
        run: |
          docker build -t product-service ./backend/microservices/product-service
          docker tag product-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/product-service:latest

      - name: Push Product Service Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/product-service:latest

  deploy-argocd:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name mern-microservices-cluster

      - name: Install ArgoCD Namespace
        run: |
          kubectl apply -f cluster-setup/argocd/namespace.yaml
     
      - name: Delete ArgoCD (if exists)
        run: |
          if kubectl get namespace argocd >/dev/null 2>&1; then
            echo "Deleting existing ArgoCD namespace..."
            kubectl delete namespace argocd --wait=true
          else
            echo "ArgoCD namespace does not exist. Skipping delete."
          fi

      - name: Install ArgoCD via Helm
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd --create-namespace


      - name: Wait for ArgoCD CRDs
        run: |
          echo "Waiting for ArgoCD CRDs..."
          kubectl wait --for=condition=Established crd/applications.argoproj.io --timeout=120s

      - name: Deploy ArgoCD Application
        run: |
          kubectl apply -f cluster-setup/argocd/app-deploy.yaml
