name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:

  # ─────────────────────────────────────────
  # JOB 1 — Build and Push Images to ECR
  # ─────────────────────────────────────────
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # ================= AUTH SERVICE =================
      - name: Build Auth Service Image
        run: |
          docker build -t auth-service ./backend/microservices/auth-service
          docker tag auth-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      - name: Push Auth Service Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      # ================= USER SERVICE =================
      - name: Build User Service Image
        run: |
          docker build -t user-service ./backend/microservices/user-service
          docker tag user-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:latest

      - name: Push User Service Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:latest

      # ================= PRODUCT SERVICE =================
      - name: Build Product Service Image
        run: |
          docker build -t product-service ./backend/microservices/product-service
          docker tag product-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/product-service:latest

      - name: Push Product Service Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/product-service:latest


  # ─────────────────────────────────────────
  # JOB 2 — Install ArgoCD + Apply App Config
  # ─────────────────────────────────────────
  deploy-argocd:
    runs-on: ubuntu-latest
    needs: build-and-push        # runs only after Job 1 succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect kubectl to EKS cluster
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Create ArgoCD namespace
        run: |
          kubectl apply -f cluster-setup/argocd/namespace.yaml

      - name: Install ArgoCD using core manifest
        run: |
          kubectl delete deployment argocd-repo-server -n argocd --ignore-not-found=true
          kubectl delete deployment argocd-server -n argocd --ignore-not-found=true
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.3/manifests/core-install.yaml


      - name: Wait for ArgoCD to be ready
        run: |
          kubectl rollout status statefulset/argocd-application-controller \
            -n argocd \
            --timeout=300s

      - name: Apply ArgoCD App (points to your k8s-deployments folder)
        run: |
          kubectl apply -f cluster-setup/argocd/app-deploy.yaml \
            --namespace argocd
